apiVersion: v1
kind: Service
metadata:
  name: cloudpath-service
  namespace: cloudpath
spec:
  type: NodePort
  selector:
    app: cloudpath-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080